### ISSUE TITLE
Please abide by the terms of the Apache license

### ISSUE THREAD

**Issue by kislyuk** [dbritto-dev/signxml_sunat#1]
Hello,

I am the author of the project you copied your work from, SignXML. Your copy does not abide by the terms of the license that I distributed the software under. Specifically, I assess that you are in violation of terms 4(a) and 4(b) of the Apache license 2.0:

> 4. Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
>
> * You must give any other recipients of the Work or Derivative Works a copy of this License; and
> * You must cause any modified files to carry prominent notices stating that You changed the files

Please modify your project and its releases to abide by the terms above.

**Comment by dbritto-dev** [comment]
Hi @kislyuk would you mind giving me more information about you are talking about. Because even if I use signxml in the name of this project both projects are completely different. So, please tell me what I copied from you project line by line. BTW, let me explain you something about this project, this project is oriented to sign xml files using SUNAT spec which is not common use case to sign xml files.

**Comment by kislyuk** [comment]
You used SignXML as the starting point of you project, then replaced all references to SignXML with your own project name (which includes the words "signxml" and "SignXML"). This is evident from the git history of your project, which includes many lines copied directly from the SignXML documentation. For example, the commit https://github.com/dbritto-dev/signxml_sunat/commit/c55880d5f1b4e3991f4f43874ba86152d2ed2207 contains a copy of a subset of the documentation for the SignXML project, including references to SignXML that you forgot to replace.

I welcome reuse of code and documentation from my project, but I require that the terms of the license that I selected be respected.

Please abide by the redistribution terms that I cited above. If I don't receive a satisfactory answer, my next step will be a message to the GitHub and PyPI abuse teams.

**Comment by dbritto-dev** [comment]
@kislyuk please do it. I didn't see any issue except for the readme but I can rewrite it if you. I won't what the project have currently because all the code except for similarities in readme is completely different.
