### ISSUE TITLE
Notice of copyright violation

### ISSUE THREAD

**Issue by kislyuk** [dbritto-dev/signxml_sunat#2]
Hello Danilo Britto (@dbritto-dev),

Your project contains material copyrighted by me (for example, your commit https://github.com/dbritto-dev/signxml_sunat/commit/c55880d5f1b4e3991f4f43874ba86152d2ed2207 contains material that I originally distributed in the https://github.com/XML-Security/signxml project). All rights are reserved and you are not permitted to use this material except as specified in the original project license.

Since you have refused to abide by the terms of the Apache License, version 2.0, as I requested in #1, you are now in violation of my copyright. Please cease and desist from distributing this copyrighted material and any derivates of that code.

**Comment by dbritto-dev** [comment]
@kislyuk please do it. BTW, apart from docs there nothing in common about these two projects.
